// Listado de provincias españolas (código y nombre), obtenido de
// GET https://api.el-tiempo.net/json/v3/provincias
export const PROVINCIAS = [
  { codProv: '15', nombre: 'A Coruña' },
  { codProv: '03', nombre: 'Alacant/Alicante' },
  { codProv: '02', nombre: 'Albacete' },
  { codProv: '04', nombre: 'Almería' },
  { codProv: '01', nombre: 'Araba/Álava' },
  { codProv: '33', nombre: 'Asturias' },
  { codProv: '05', nombre: 'Ávila' },
  { codProv: '06', nombre: 'Badajoz' },
  { codProv: '08', nombre: 'Barcelona' },
  { codProv: '48', nombre: 'Bizkaia' },
  { codProv: '09', nombre: 'Burgos' },
  { codProv: '10', nombre: 'Cáceres' },
  { codProv: '11', nombre: 'Cádiz' },
  { codProv: '39', nombre: 'Cantabria' },
  { codProv: '12', nombre: 'Castelló/Castellón' },
  { codProv: '51', nombre: 'Ceuta' },
  { codProv: '13', nombre: 'Ciudad Real' },
  { codProv: '14', nombre: 'Córdoba' },
  { codProv: '16', nombre: 'Cuenca' },
  { codProv: '20', nombre: 'Gipuzkoa' },
  { codProv: '17', nombre: 'Girona' },
  { codProv: '18', nombre: 'Granada' },
  { codProv: '19', nombre: 'Guadalajara' },
  { codProv: '21', nombre: 'Huelva' },
  { codProv: '22', nombre: 'Huesca' },
  { codProv: '07', nombre: 'Illes Balears' },
  { codProv: '23', nombre: 'Jaén' },
  { codProv: '26', nombre: 'La Rioja' },
  { codProv: '35', nombre: 'Las Palmas' },
  { codProv: '24', nombre: 'León' },
  { codProv: '25', nombre: 'Lleida' },
  { codProv: '27', nombre: 'Lugo' },
  { codProv: '28', nombre: 'Madrid' },
  { codProv: '29', nombre: 'Málaga' },
  { codProv: '52', nombre: 'Melilla' },
  { codProv: '30', nombre: 'Murcia' },
  { codProv: '31', nombre: 'Navarra' },
  { codProv: '32', nombre: 'Ourense' },
  { codProv: '34', nombre: 'Palencia' },
  { codProv: '36', nombre: 'Pontevedra' },
  { codProv: '37', nombre: 'Salamanca' },
  { codProv: '38', nombre: 'Santa Cruz de Tenerife' },
  { codProv: '40', nombre: 'Segovia' },
  { codProv: '41', nombre: 'Sevilla' },
  { codProv: '42', nombre: 'Soria' },
  { codProv: '43', nombre: 'Tarragona' },
  { codProv: '44', nombre: 'Teruel' },
  { codProv: '45', nombre: 'Toledo' },
  { codProv: '46', nombre: 'València/Valencia' },
  { codProv: '47', nombre: 'Valladolid' },
  { codProv: '49', nombre: 'Zamora' },
  { codProv: '50', nombre: 'Zaragoza' }
]